#pragma once

// From glfw3.h
#define VITAR_MOUSE_BUTTON_1         0
#define VITAR_MOUSE_BUTTON_2         1
#define VITAR_MOUSE_BUTTON_3         2
#define VITAR_MOUSE_BUTTON_4         3
#define VITAR_MOUSE_BUTTON_5         4
#define VITAR_MOUSE_BUTTON_6         5
#define VITAR_MOUSE_BUTTON_7         6
#define VITAR_MOUSE_BUTTON_8         7
#define VITAR_MOUSE_BUTTON_LAST      VITAR_MOUSE_BUTTON_8
#define VITAR_MOUSE_BUTTON_LEFT      VITAR_MOUSE_BUTTON_1
#define VITAR_MOUSE_BUTTON_RIGHT     VITAR_MOUSE_BUTTON_2
#define VITAR_MOUSE_BUTTON_MIDDLE    VITAR_MOUSE_BUTTON_3